### ISSUE TITLE
Issue tracker for fix migration to 2201.0.5 

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#1026]
**Description:**
This issue is created for tracking purpose of fixes which are in openapi tool from choreo.

- [x] https://github.com/ballerina-platform/openapi-tools/issues/952
- [x] https://github.com/ballerina-platform/openapi-tools/issues/979
- [x] https://github.com/ballerina-platform/openapi-tools/issues/977
- [x] https://github.com/ballerina-platform/openapi-tools/issues/993
- [x] https://github.com/ballerina-platform/openapi-tools/issues/1003

**Describe your task(s)**
These above fixes were already added in Swanlake **update 01** and the coming **update 01 patch** version, good to have **2201.0.5** patch version.
points 3

**Comment by lnash94** [comment]
Fixes were migrated favour with this pr https://github.com/ballerina-platform/openapi-tools/pull/1009
