### ISSUE TITLE
Verifying the support for OpenAPI version 3.1.0  while generating Ballerina codes

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#1399]
**Description:**
OpenAPI 3.1.0 and 3.0.x version has shown inconsistent behaviour for the scenarios when generating the ballerina code.

In [this doc](https://docs.google.com/document/d/1Y__2YvPmzOdL9Iexu-FciMkL80liuXZw1WRnAnHBKW8/edit?usp=sharing) we have summarized the changes and new features introduced with OpenAPI 3.1. 

First we have planned to integrate the support to the changes added to the existing OpenAPI syntaxes. 

- [x] Support `null` data type. The `type` of a OpenAPI schema is no longer a single value. It is an array. 
- [x] Revisit the usages of `exclusiveMinimum` and `exclusiveMaximum`
- [x] Check the compatibility of the Ballerina type generation with Json Schema
       - Parser is not flattening the composed schemas in parameters. https://github.com/ballerina-platform/openapi-tools/issues/1332

While supporting these changes, the corresponding tests are needed to add covering below scenarios. 

- [x] Add tests to check the compatibility with the current existing openAPI specification with version 3.1.x 
- [x] Add tests cases to cover migration changes and newly introduced features in openAPI 3.0.x to 3.1.x  https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

**Comment by aneeshafedo** [comment]
Please find more details in here [https://docs.google.com/document/d/1Y__2YvPmzOdL9Iexu-FciMkL80liuXZw1WRnAnHBKW8/edit?usp=sharing](https://docs.google.com/document/d/1Y__2YvPmzOdL9Iexu-FciMkL80liuXZw1WRnAnHBKW8/edit?usp=sharing)

**Comment by aneeshafedo** [comment]
**Task : Check the compatibility of the Ballerina type generation with Json Schema**

*   [ ] Remove casting to specific schemas to access the properties. From parser 2.2.0 the Schema class is common for any schema and with OpenAPI 3.1.0, all the schemas are mapped to JSON schema. 
*   [ ] References in parameter schemas are not getting resolved. Implementation is added to get the component from the reference name
*   [ ] Added diagnotic tests with new 3.1.0 specs and also upgrading the existing 3.0 OpenAPIs to 3.1.0

**Comment by aneeshafedo** [comment]
**Task :  Revisit the usages of `exclusiveMinimum` and `exclusiveMaximum`**

*   [x] Considered `exclusiveMinimumValue` and `exclusiveMaximumValue` from the parser when generating the constraints
*   [x] If both `minimum` and `exclusiveMinimum` is given, only the `minimum` value is considered
*   [x] Added relavant tests

**Comment by aneeshafedo** [comment]
**Task : Support `null` data type**

*   [x] Replace `schema.getType` usage to `schema.getTypes` to be compatible with both 3.0 and 3.1 OpenAPI specs
*   [x] When getting a type of a field, get the first non-null type fro the array of types. Ignored the other types for now since how to address multiple non-null types is not clearly mentioned in anywhere.

**Comment by aneeshafedo** [comment]
With the reference not resolving issues (swagger-api/swagger-parser#1950) with OpenAPI 3.1 parser, the implementation is added to resolve the references from our end.
